### ISSUE TITLE
Fix Light House Score, Problems in Code Blocks

### ISSUE THREAD

**Issue by Suleman-Elahi** [danielcgilibert/blog-template#11]
Right now, it has issues with the post page on the copy button in code blocks.

Solution: Add `aria-label="Name"` property in the `<button>` tags

![image](https://github.com/danielcgilibert/blog-template/assets/24384996/0f60f4d2-6d62-47f4-baf8-929266010517)

**Color contrast ratio:**

![image](https://github.com/danielcgilibert/blog-template/assets/24384996/b29b0db0-a599-489a-a1c7-b83c61376398)

background color for code blocks needs to be changed to more darker color or black.

**Comment by danielcgilibert** [comment]
Thank you for opening the issue, if you want to send a pull request, you are welcome.
