### ISSUE TITLE
Slug creatuoy

### ISSUE THREAD

**Issue by ahmadkakarr** [danielcgilibert/blog-template#15]
I want to create slug based on categories to which blog post belongs.

Example.com/category1/post1

Also clicking on category1
https://blog-template-gray.vercel.app/category/category-1

I think it should be just

https://blog-template-gray.vercel.app/category-1

please guide how can i do this?

**Comment by danielcgilibert** [comment]
Hi @ahmadkakarr to create that slug you simply have to rename the category folder to [...category] and change the links to the categories.

I have created a branch with the code: [code](https://github.com/danielcgilibert/blog-template/commit/942d4cbff747a0f46c9f98eb547dfa2f2c064da1#diff-0e6f867620916103319b14c385e497988bc5e577700045af6a50e6e33b7ade77)
