### ISSUE TITLE
Mobile usage

### ISSUE THREAD

**Issue by n-tdi** [danielcgilibert/blog-template#20]
Wonderful blog template! The only issues that arise are when on mobile, specifically iphone 13, the dark mode button overlaps weirdly, and the hamburger menu looks really off. ![image](https://github.com/danielcgilibert/blog-template/assets/79174456/a3c04ea3-e154-4f98-9c12-373a370dab07)
![image](https://github.com/danielcgilibert/blog-template/assets/79174456/c347a3e2-77db-486d-97c4-b0ab6bc49e70)

**Comment by danielcgilibert** [comment]
Thank you for submitting the issue, I will review it.
