### ISSUE TITLE
No title shows up on each blog post page while on mobile phone

### ISSUE THREAD

**Issue by yudiqing** [danielcgilibert/blog-template#34]
On each blog post page, there is no showing of title (see the attachment) on mobile edge or other mobile browser. I know on desktop version, the title will have an animation to slide in. 

Is there anyway to disable the slide-in animation effect? 

![IMG_E03EE0B8B977-1](https://github.com/danielcgilibert/blog-template/assets/10558727/12919293-a720-4bf5-8381-47d1c05d9239)

**Comment by danielcgilibert** [comment]
Hello, could you tell me which browser you are using? To remove the animation in the blogPost file in Layouts, delete the script :
```
<script>
import { animate } from 'motion'

	animate(
		'.title',
		{
			opacity: [0, 1],
			clipPath: ['polygon(0 0, 0 0, 0 100%, 0% 100%)', 'polygon(100% 0, 0 0, 0 100%, 100% 100%)']
		},
		{ duration: 1, easing: 'ease-in-out' }
	)
</script>
```

and in the title, remove the class opacity-0

```
<h1 class='title text-center text-4xl md:text-6xl md:pb-2.5 font-semibold    ---> opacity-0'>
{title}
</h1>
```

**Comment by yudiqing** [comment]
Daniel: thanks. The browser was on Edge, iphone 15.
