### ISSUE TITLE
Pagination works locally but not after deployment on the domain

### ISSUE THREAD

**Issue by hongscave** [danielcgilibert/blog-template#45]
Hi guys, thanks for this template, love it. But I ran into an issue.

I have a finance category, for both run dev and run build (then preview) works normally.
However, when I deployed it to my cloudflare host, the url for next page became 
example.com/category/finance/1/2
instead of:
example.com/category/finance/2

This is weird. How can I fix this? Is this a bug?
I made sure cloudflare us using the same version of node as my local(21.1.0) and tried netlify with same result.

**Comment by borgfriend** [comment]
I had the same issue.  I looked into it and fixed the url generation.

Here is the PR for it https://github.com/danielcgilibert/blog-template/pull/47

**Comment by hongscave** [comment]
> I had the same issue. I looked into it and fixed the url generation.
> 
> Here is the PR for it #47

Can confirm it's working. Thanks!
